# 自定义属性  project\controller\MistraController.java
my:
  name:  RoronoaZoro丶小王瑞
# 将自定义属性复制给实体类,每次启动项目时赋值一次  project\entity\ConfigurationParameter.java
pojo:
  name: RoronoaZoro丶小王瑞
  age: 18
  number:  ${random.int}
  uuid : ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  describe: 你的名字${pojo.name},非得等到自己开始讨厌自己了,才懂得怎么诚实面对自己想要的。

#查看当前项目中已启用和未启用的自动配置的报告
debug: true
# 数据库访问配置,主数据源，默认的
spring:
  # 不同环境配置文件切换 dev  prod  test
  profiles:
    active: dev
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.38.117:3306/springboot?useUnicode=true&amp;characterEncoding=UTF-8
    username: mistra
    password: 123456
    # 初始化大小，最小，最大
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  jpa:
    hibernate:
          # 自动创建、更新、验证数据库表结构
          ddl-auto: update  # 第一次简表create  后面用update
    # 显示sql
    show-sql: true






